{{- if .Values.jobs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jobs-grpc
  labels:
    app: jobs
spec:
  type: ClusterIP
  selector:
    app: jobs
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
{{- end }}