global:
  imagePullPolicy: Always

pulsar:
  namespace: pulsar
  namespaceCreate: true
  zookeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  broker:
    replicaCount: 1
    podMonitor:
      enabled: false
  bookkeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  autorecovery:
    podMonitor:
      enabled: false
  proxy:
    replicaCount: 1
    podMonitor:
      enabled: false
  kube-prometheus-stack:
    enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus: 
      enabled: false
  
postgresql:
  namespaceOverride: postgresql
  auth: 
    username: postgres
    password: postgres
    database: jobster
  primary:
    initdb:
      scripts:
        create-dbs.sql: |
          CREATE DATABASE auth;
          CREATE DATABASE products;
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.1.0-debian-12-r0


jobs: 
  enabled: true
  replicas: 1
  image: '563149050413.dkr.ecr.eu-west-1.amazonaws.com/jobster/jobs:latest'
  port: 3001

executor:
  enabled: true
  replicas: 1
  image: '563149050413.dkr.ecr.eu-west-1.amazonaws.com/jobster/executor:latest'
  port: 3002

auth:
  enabled: true
  replicas: 1
  image: '563149050413.dkr.ecr.eu-west-1.amazonaws.com/jobster/auth:latest'
  port: 
    http: 3000
    grpc: 5000
  jwt:
    secret: kLcv5p09Q7J0Nb8uclUQW8UIdkxP9PUV
    expirationMs: "28800000"

products:
  enabled: true
  replicas: 1
  image: '563149050413.dkr.ecr.eu-west-1.amazonaws.com/jobster/products:latest'
  port: 
    http: 3003
    grpc: 5001